import type { Language } from '@/contexts/language-context'

export const PDF_LABELS: Record<
  Language,
  {
    brand: string
    progressPlan: string
    atAGlance: string
    aboutYou: string
    whoYouSeemToBe: string
    apparentFocus: string
    motivationDrivers: string
    whereAttentionWent: string
    tasksCompleted: string
    projects: string
    goals: string
    swotAnalysis: string
    strengths: string
    weaknesses: string
    opportunities: string
    threats: string
    executiveSummary: string
    highlights: string
    moduleHighlights: string
    accomplishments: string
    generatedBy: string
    totalPoints: string
    tasksCompletedStat: string
    tasksCreated: string
    projectsCompleted: string
    habitCompletions: string
    topCategories: string
    goalProgress: string
    interactions: string
    reportTitle: string
  }
> = {
  en: {
    brand: 'Life Stacks',
    progressPlan: 'Progress Plan',
    atAGlance: 'At a glance',
    aboutYou: 'About you',
    whoYouSeemToBe: 'Who you seem to be',
    apparentFocus: 'What you seem focused on',
    motivationDrivers: 'What appears to drive your motivation',
    whereAttentionWent: 'Where your attention went',
    tasksCompleted: 'Tasks you completed',
    projects: 'Projects',
    goals: 'Goals',
    swotAnalysis: 'SWOT analysis',
    strengths: 'Strengths',
    weaknesses: 'Weaknesses',
    opportunities: 'Opportunities',
    threats: 'Threats',
    executiveSummary: 'Executive summary',
    highlights: 'Highlights',
    moduleHighlights: 'Life Hacks — module highlights',
    accomplishments: 'Accomplishments',
    generatedBy: 'Generated by Life Stacks',
    totalPoints: 'Total points earned',
    tasksCompletedStat: 'Tasks completed',
    tasksCreated: 'Tasks created',
    projectsCompleted: 'Projects completed',
    habitCompletions: 'Habit completions',
    topCategories: 'Top task categories',
    goalProgress: 'Goal',
    interactions: 'interactions',
    reportTitle: 'Progress Report',
  },
  es: {
    brand: 'Life Stacks',
    progressPlan: 'Plan de Progreso',
    atAGlance: 'De un vistazo',
    aboutYou: 'Sobre ti',
    whoYouSeemToBe: 'Quién pareces ser',
    apparentFocus: 'En qué pareces enfocarte',
    motivationDrivers: 'Qué parece impulsar tu motivación',
    whereAttentionWent: 'Dónde pusiste tu atención',
    tasksCompleted: 'Tareas que completaste',
    projects: 'Proyectos',
    goals: 'Objetivos',
    swotAnalysis: 'Análisis FODA',
    strengths: 'Fortalezas',
    weaknesses: 'Debilidades',
    opportunities: 'Oportunidades',
    threats: 'Amenazas',
    executiveSummary: 'Resumen ejecutivo',
    highlights: 'Destacados',
    moduleHighlights: 'Life Hacks — módulos destacados',
    accomplishments: 'Logros',
    generatedBy: 'Generado por Life Stacks',
    totalPoints: 'Puntos totales ganados',
    tasksCompletedStat: 'Tareas completadas',
    tasksCreated: 'Tareas creadas',
    projectsCompleted: 'Proyectos completados',
    habitCompletions: 'Completaciones de hábitos',
    topCategories: 'Categorías principales de tareas',
    goalProgress: 'Objetivo',
    interactions: 'interacciones',
    reportTitle: 'Informe de Progreso',
  },
}

export function getPdfLabels(language?: Language): (typeof PDF_LABELS)['en'] {
  return PDF_LABELS[language === 'es' ? 'es' : 'en']
}
